### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by maxime-granger** [peted-davis/WeatherFlow_PiConsole#105]
Since the past couple of updates I get the following error message when I try to start the console not sure where to start on how to resolve it. 

Last login: Thu May 11 13:14:22 2023 from 192.168.91.56
maime@maime-Surface-3:~$ wfpiconsole start
[INFO   ] [Logger      ] Record log in /home/maime/.kivy/logs/kivy_23-05-11_33.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/maime/.local/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
 Traceback (most recent call last):
   File "main.py", line 28, in <module>
     from lib     import config as configFile
   File "/home/maime/wfpiconsole/lib/config.py", line 24, in <module>
     import requests
   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
     from urllib3.contrib import pyopenssl
   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
     import OpenSSL.SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
     from OpenSSL import crypto, SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3279, in <module>
     _lib.OpenSSL_add_all_algorithms()
 AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
 Error in sys.excepthook:
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
     from apport.fileutils import likely_packaged, get_recent_crashes
   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
     from apport.report import Report
   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
     import apport.fileutils
   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
     import requests
   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
     from urllib3.contrib import pyopenssl
   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
     import OpenSSL.SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
     from OpenSSL import crypto, SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3279, in <module>
     _lib.OpenSSL_add_all_algorithms()
 AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

 Original exception was:
 Traceback (most recent call last):
   File "main.py", line 28, in <module>
     from lib     import config as configFile
   File "/home/maime/wfpiconsole/lib/config.py", line 24, in <module>
     import requests
   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
     from urllib3.contrib import pyopenssl
   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
     import OpenSSL.SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
     from OpenSSL import crypto, SSL
   File "/home/maime/.local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3279, in <module>
     _lib.OpenSSL_add_all_algorithms()
 AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Hardware/OS/Version (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Hardware: Surface Pro3
 - Console Version: v23.3.1

**Comment by peted-davis** [comment]
Try running

`python3 -m pip install --upgrade PyOpenSSL`

And then start the console again

**Comment by maxime-granger** [comment]
thank you
