### ISSUE TITLE
New updated version fails on startup

### ISSUE THREAD

**Issue by Jamesbenn2002** [peted-davis/WeatherFlow_PiConsole#46]
Below is a portion of the startup messaging.  There is a warning about the MenuButton class and a SunriseSunset attribute error.  I was hesitant to upgrade the code because I've a number of modifications.  Including adding the bme680 sensor capture indoor temp, humidity and air quality in a new button panel.  Plus pulling forecast data from OpenWeather and displaying in a new panel.  And a few of other minor changes.  But I did not make any changes to the SunriseSunset panel.  

I'm thinking I may be better off going back to the previous version.  If my modifications are going to conflict with the new release.  What is the best way to go back to the previous version? My code modifications are backed up.

  Thanks,  Barry....

[WARNING] [Factory     ] Ignored class "MenuButton" re-declaration. Current -  module: None, cls: <class '__main__.MenuButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Button, filename: /home/pi/wfpiconsole/kvlang/panelLayout.kv.
2022-03-09 08:55:19-0500 [-] Traceback (most recent call last):
2022-03-09 08:55:19-0500 [-]   File "main.py", line 1182, in <module>
2022-03-09 08:55:19-0500 [-]     wfpiconsole().run()
2022-03-09 08:55:19-0500 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 949, in run
2022-03-09 08:55:19-0500 [-]     self._run_prepare()
2022-03-09 08:55:19-0500 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
2022-03-09 08:55:19-0500 [-]     root = self.build()
2022-03-09 08:55:19-0500 [-]   File "main.py", line 302, in build
2022-03-09 08:55:19-0500 [-]     astro.SunriseSunset(self.Astro,self.config)
2022-03-09 08:55:19-0500 [-] AttributeError: module 'lib.astronomical' has no attribute 'SunriseSunset'

**Comment by peted-davis** [comment]
Yes, it looks like your modifications are conflicting with the new release. Sorry! I did a lot of work rewriting the structure of the code to make it more logical and expandable. Much of the functionality is the same, but some methods have been moved into classes (like the SunriseSunset method) and where they are called in the code has changed. You could probably apply your modifications to the new code (especially as there is now a fixed template for defining custom panels), but it will take time.

The best way to roll back is to download the source code from Github for v4.0.4: https://github.com/peted-davis/WeatherFlow_PiConsole/releases/tag/v4.0.4
